"""add response_note to tickets

Revision ID: 0003c0d56c4a
Revises: ba14d18914a0
Create Date: 2026-09-02 09:29:35.146965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003c0d56c4a'
down_revision: Union[str, Sequence[str], None] = 'ba14d18914a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('response_note', sa.Text(), nullable=True))
    op.add_column('visit_logs', sa.Column('blood_sugar', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visit_logs', 'blood_sugar')
    op.drop_column('tickets', 'response_note')
    # ### end Alembic commands ###
