"""Initial clean migration

Revision ID: ba14d18914a0
Revises: 
Create Date: 2026-08-20 15:10:00.065766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba14d18914a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chvs',
    sa.Column('chv_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chv_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_chvs_chv_id'), 'chvs', ['chv_id'], unique=False)
    op.create_table('location',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_revoked_tokens_token'), 'revoked_tokens', ['token'], unique=False)
    op.create_table('mothers',
    sa.Column('mother_id', sa.UUID(), nullable=False),
    sa.Column('chv_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('location_name', sa.String(length=100), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chv_id'], ['chvs.chv_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('mother_id')
    )
    op.create_table('pregnancies',
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('mother_id', sa.UUID(), nullable=False),
    sa.Column('last_menstrual_period', sa.DateTime(), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=False),
    sa.Column('gestational_age', sa.Integer(), nullable=False),
    sa.Column('pregnancy_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.mother_id'], ),
    sa.PrimaryKeyConstraint('pregnancy_id')
    )
    op.create_index(op.f('ix_pregnancies_pregnancy_id'), 'pregnancies', ['pregnancy_id'], unique=False)
    op.create_table('visit_logs',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('mother_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('chv_id', sa.UUID(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('gestational_age', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=False),
    sa.Column('logged_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_level', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chv_id'], ['chvs.chv_id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.mother_id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.pregnancy_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_visit_logs_chv_id'), 'visit_logs', ['chv_id'], unique=False)
    op.create_index(op.f('ix_visit_logs_mother_id'), 'visit_logs', ['mother_id'], unique=False)
    op.create_index(op.f('ix_visit_logs_pregnancy_id'), 'visit_logs', ['pregnancy_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('risk_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('mother_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=False),
    sa.Column('pdf_password', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mother_id'], ['mothers.mother_id'], ),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.pregnancy_id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visit_logs.visit_id'], ),
    sa.PrimaryKeyConstraint('risk_id')
    )
    op.create_index(op.f('ix_risk_assessments_risk_id'), 'risk_assessments', ['risk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_risk_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_visit_logs_pregnancy_id'), table_name='visit_logs')
    op.drop_index(op.f('ix_visit_logs_mother_id'), table_name='visit_logs')
    op.drop_index(op.f('ix_visit_logs_chv_id'), table_name='visit_logs')
    op.drop_table('visit_logs')
    op.drop_index(op.f('ix_pregnancies_pregnancy_id'), table_name='pregnancies')
    op.drop_table('pregnancies')
    op.drop_table('mothers')
    op.drop_index(op.f('ix_revoked_tokens_token'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_chvs_chv_id'), table_name='chvs')
    op.drop_table('chvs')
    # ### end Alembic commands ###
